### PR TITLE
OSFUSE-250: Review Karaf based quickstarts and templates

### PR DESCRIPTION
**Pull request by lburgazzoli**

### CODE REVIEW

**Comment by lburgazzoli** [comment]
@jimmidyson @dhirajsb 

this pr fails because it does not find the -redhat artifacts in maven central, would it be possible to run the mvn build with -s configuration/settings.xml ?

**Comment by lburgazzoli** [comment]
@jimmidyson @dhirajsb never mind, solved it by setting repos in pom

**Comment by jstrachan** [comment]
[merge]

**Comment by jstrachan** [comment]
add to whitelist

**Pull request merged**
